server:
  port: 8081


diagnostic:
  apiKey: BV98TrYgvc
  apiSecret: hoSqI07NXMwNZrJUbVso2yo5YbhpiT7O
  appName:  Example App
#  handler:
#    numberOfThreads: 5
#    batchSize: 100
#    delay: 5000
#    publishLevel: INFO




#  mvn deploy:deploy-file -Durl=file:///C:/Users/josep/IdeaProjects/diagnosit-example/repo/ -Dfile=C:/Users/josep/IdeaProjects/syck-diagnostic-parent/syck-diagnostic-starter/target/syck-diagnostic-starter-1.0-SNAPSHOT.jar -DgroupId=com.syck -DartifactId=syck-diagnostic-starter -Dpackaging=jar -Dversion=1.0-SNAPSHOT
